### PR TITLE
fix(filemanager): add permissions for analysis and fastq archive buckets

### LINKED ISSUE #790: Filemanager: Tracking archived objects
According to the [moved objects docs](https://github.com/umccr/orcabus/blob/main/lib/workload/stateless/stacks/filemanager/docs/MOVED_OBJECTS.md) the filemanager should be able to keep track of archived objects.

For example 

@victorskl has relocated the file 

```
s3://pipeline-prod-cache-503977275616-ap-southeast-2/byob-icav2/production/analysis/wts/20220416e17de179/MDX220129_somalier/MDX220129.somalier
```

To

```
s3://archive-prod-analysis-503977275616-ap-southeast-2/v1/year=2022/month=04/20220416e17de179/MDX220129_somalier/MDX220129.somalier
```

However, I cannot query the original file with the file manager since

```
curl \
  --fail-with-body --silent --show-error --location \
  --request GET \
  --header "Authorization: Bearer $ORCABUS_TOKEN" \
  --url "https://file.prod.umccr.org/api/v1/s3?bucket=pipeline-prod-cache-503977275616-ap-southeast-2&key=byob-icav2/production/analysis/wts/20220416e17de179/MDX220129_somalier/MDX220129.somalier" | \
jq --raw-output
```

Gives

```json
{
  "links": {
    "previous": null,
    "next": null
  },
  "pagination": {
    "count": 0,
    "page": 1,
    "rowsPerPage": 1000
  },
  "results": []
}
```

But when I find the file in the archive I get

```
curl \
  --fail-with-body --silent --show-error --location \
  --request GET \
  --header "Authorization: Bearer $ORCABUS_TOKEN" \
  --url "https://file.prod.umccr.org/api/v1/s3?bucket=archive-prod-analysis-503977275616-ap-southeast-2&key=v1/year=2022/month=04/20220416e17de179/MDX220129_somalier/MDX220129.somalier" | \
jq --raw-output '.results'
```

I get 

```
[
    {
      "s3ObjectId": "0193b43a-4452-7e41-9318-87436c4e0c30",
      "eventType": "Created",
      "bucket": "archive-prod-analysis-503977275616-ap-southeast-2",
      "key": "v1/year=2022/month=04/20220416e17de179/MDX220129_somalier/MDX220129.somalier",
      "versionId": "PD9SJuPhKpqGZUvVmrN0cwQ7slGBKuPk",
      "eventTime": "2024-12-11T05:38:56Z",
      "size": 207218,
      "sha256": null,
      "lastModifiedDate": null,
      "eTag": "\"389da6eec04b7d389d0a7312a03289b5\"",
      "storageClass": null,
      "sequencer": "0067592570BC5197CB",
      "isDeleteMarker": false,
      "numberDuplicateEvents": 0,
      "attributes": null,
      "deletedDate": null,
      "deletedSequencer": null,
      "numberReordered": 0,
      "ingestId": null,
      "isCurrentState": true
    }
  ]
```

But the ingestId is null?

Ideally I'd be able to track through the ingest id as per the docs?

For context, I'm looking into appropriate database fields in the fastq list row manager.  
'is_archived' will likely be a boolean field along with `read_1_s3_object_id` and `read_2_s3_object_id`.  
If a fastq pair is restored from archive, I'd like to be able to update some identifier to instead point to the new location but once that temporarily restored pair has been deleted, the database should instead point to the identifiers that represent the archived files.

### PR DESCRIPTION
**Pull request by mmalenic**
Closes #790 

### Changes
* Fixes missing permissions that let the filemanager tag objects in the archive analysis and fastq buckets.

### CODE REVIEW

**Comment by victorskl** [comment]
.. reviewing

File: config/stacks/fileManager.ts [hunk 1]
```diff
@@ -21,6 +23,12 @@ export const getFileManagerStackProps = (stage: AppStage): FilemanagerConfig =>
     inventorySourceBuckets.push(fileManagerInventoryBucket[stage]);
   }
 
+  const eventSourceBuckets = [oncoanalyserBucket[stage], icav2PipelineCacheBucket[stage]];
+  if (stage == AppStage.PROD) {
```
Comment (alexiswl) [inline config/stacks/fileManager.ts:27]: Might be worth putting in a comment here to say 'we only archive production data'

**Review by alexiswl — APPROVED** [review]

**Review by victorskl — APPROVED** [review]
Right! LGTM. Thanks for quick fix.
