### PR TITLE
fix(filemanager) change i32 to i64 to support bigger sizes

### LINKED ISSUE #217: filemanager: use i64 instead of i32
The data type on the filemanager's event [message](https://github.com/umccr/orcabus/blob/b0fc25849a4922a18ec407dc903baa29f7aa9e7e/lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs#L99) size should be i64 to accommodate larger file sizes.

### PR DESCRIPTION
**Pull request by mmalenic**
Closes #217

### Changes
* Replace i32 with i64.
* Replace integer with bigint.

### CODE REVIEW

File: lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs [hunk 1]
```diff
@@ -291,6 +291,35 @@ pub(crate) mod tests {
...
+    #[sqlx::test(migrator = "MIGRATOR")]
+    async fn ingest_object_created_large_size(pool: PgPool) {
+        let mut events = test_events();
+        events.object_deleted = Default::default();
+
+        events
+            .object_created
+            .sizes
+            .iter_mut()
+            .for_each(|size| *size = Some(373588380934135341));
```
Comment (brainstorm) [inline lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs:303]: I'd substitute this magic number for some `std::` constant if possible?

File: lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs [hunk 2]
```diff
@@ -291,6 +291,35 @@ pub(crate) mod tests {
...
+        let ingester = test_ingester(pool);
+        ingester.ingest_events(events).await.unwrap();
+
+        let (object_results, s3_object_results) = fetch_results(&ingester).await;
+
+        assert_eq!(object_results.len(), 1);
+        assert_eq!(s3_object_results.len(), 1);
+        assert_with(
+            &s3_object_results[0],
+            Some(373588380934135341),
```
Comment (brainstorm) [inline lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs:314]: Ditto

File: lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs [hunk 3]
```diff
@@ -162,13 +162,58 @@ impl From<Message> for FlatS3EventMessages {
...
+                    "arn:aws:s3:::bucket"
+                ],
+                "detail": {{
+                    "version": "0",
+                    "bucket": {{
+                        "name": "bucket"
+                    }},
+                    "object": {{
+                        "key": "key",
+                        "size": 373588380934135341,
```
Comment (brainstorm) [inline lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs:194]: Ahh, I see where the number comes from now... maybe we can be cheeky and alter the example so that it matches an already known constant in std? ;)

**Review by brainstorm — CHANGES_REQUESTED** [review]

File: lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs (hunk 3 above)
Comment (mmalenic) [reply lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs:194]: Good call, I'll replace it with [`i64::MAX`](https://doc.rust-lang.org/std/primitive.i64.html#associatedconstant.MAX). May as well test the biggest value here.

**Review by brainstorm — APPROVED** [review]
Delicious! ;)
